### ISSUE TITLE
[to discuss] drop integration branch for mfserv/base/admin/sysmon/data repositores

### ISSUE THREAD

**Issue by thefab** [metwork-framework/resources#49]
ping @thebaptiste

**Comment by thebaptiste** [comment]
I'm not convinced that this a good idea.
Sometimes we do a little change in mfext (or in another repository used or built in mfext, such as log_proxy), we don't test it in a whole experimental branch because we don't expect any linked problem in mfserv/data/base/admin/sysmon but, bad luck, there is one, and so the integration branch is broken for some modules.
If we suppressed the integration branch for mfserv/data/base/admin/sysmon, it will sometimes happen in the master branch. We don't want it, do we ?
